version: '3.9'

services:
  web:
    build: .
    command: python /Articles/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Articles
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
